'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import book from '@/content/book.json';
import {getBookProgress,markBook} from '@/lib/account';
type Chapter=typeof book.chapters[number];
export function BookCourse({chapterId}:{chapterId?:string}){
 const [progress,setProgress]=useState<Record<string,boolean>>({});
 useEffect(()=>{const sync=()=>setProgress(getBookProgress());sync();window.addEventListener('py-term-progress',sync);return()=>window.removeEventListener('py-term-progress',sync);},[]);
 const chapter=book.chapters.find(c=>c.id===chapterId);
 if(chapter)return <ChapterView key={chapter.id} chapter={chapter} progress={progress}/>;
 return <main className="learning-home book-home"><p className="eyebrow">КНИЖНЫЙ КУРС / {book.author}</p><h1>{book.title}</h1><p className="book-intro">Читайте главу в своей книге, затем проверьте понимание. В каждом тесте — три вопроса, разбор ответа и наглядная последовательность шагов.</p><div className="book-summary"><span><strong>{book.chapters.filter(c=>progress[`${c.id}:read`]).length}/16</strong> глав прочитано</span><span><strong>{book.chapters.filter(c=>c.questions.every(q=>progress[q.id])).length}/16</strong> тестов пройдено</span><span>{book.edition}<br/>Номера страниц — печатные</span></div><div className="book-grid">{book.chapters.map(c=>{const done=c.questions.filter(q=>progress[q.id]).length;return <Link key={c.id} href={`/app/book/${c.id}`} className="book-card"><div className="book-spine"><span>ГЛАВА {String(c.number).padStart(2,'0')}</span><span>с. {c.start}–{c.end}</span></div><h2>{c.title}</h2><p>{c.focus}</p><div className="book-card-status"><span>{progress[`${c.id}:read`]?'✓ Прочитано':'○ Не прочитано'}</span><span>{done}/3 ответа</span></div><progress max={3} value={done}/></Link>})}</div><p className="book-source">Вопросы и схемы составлены для платформы по предоставленному изданию. Они не являются заданиями автора. Полный текст книги здесь не публикуется. <a href={book.companion} target="_blank" rel="noreferrer">Код к книге от автора ↗</a></p></main>;
}
function ChapterView({chapter:c,progress}:{chapter:Chapter;progress:Record<string,boolean>}){
 const [index,setIndex]=useState(0),[answer,setAnswer]=useState<number|null>(null),[submitted,setSubmitted]=useState(false),[error,setError]=useState('');
 const q=c.questions[index],correct=answer===q.correct,passed=c.questions.every(q=>progress[q.id]);
 function next(i:number){setIndex(i);setAnswer(null);setSubmitted(false);}
 function check(){if(answer===null)return;setSubmitted(true);if(answer===q.correct){try{markBook(q.id,true);}catch{setError('Не удалось сохранить ответ. Проверьте хранилище браузера.');}}}
 return <main className="learning-home book-chapter"><Link className="back-link" href="/app/book">← Все главы</Link><header className="book-chapter-heading"><p className="eyebrow">ГЛАВА {c.number} / с. {c.start}–{c.end}</p><h1>{c.title}</h1><p>{c.focus}</p><label className="book-read"><input type="checkbox" checked={!!progress[`${c.id}:read`]} onChange={e=>{try{markBook(`${c.id}:read`,e.target.checked);}catch{setError('Не удалось сохранить отметку.');}}}/><span>Я прочитал главу</span></label></header>{error&&<p role="alert">{error}</p>}<div className="book-learning-layout"><section className="book-quiz"><div className="quiz-heading"><h2>Проверка понимания</h2><span>{index+1} / {c.questions.length}</span></div><nav className="quiz-dots" aria-label="Вопросы главы">{c.questions.map((question,i)=><button key={question.id} aria-current={i===index?'step':undefined} onClick={()=>next(i)} aria-label={`Вопрос ${i+1}${progress[question.id]?', пройден':''}`}>{i+1}{progress[question.id]&&' ✓'}</button>)}</nav><fieldset className="book-answers" key={q.id} disabled={submitted}><legend>{q.prompt}</legend>{q.options.map((option,i)=><label key={option} className={`${answer===i?'selected':''} ${submitted&&i===q.correct?'correct':''} ${submitted&&answer===i&&!correct?'incorrect':''}`}><input type="radio" name={q.id} checked={answer===i} onChange={()=>setAnswer(i)}/><b>{String.fromCharCode(65+i)}</b><span>{option}</span>{submitted&&i===q.correct&&<span aria-label="Правильный ответ">✓</span>}</label>)}</fieldset>{!submitted?<button className="primary" disabled={answer===null} onClick={check}>Проверить ответ</button>:<div className={`book-feedback ${correct?'correct':'incorrect'}`} role="status"><h3>{correct?'✓ Верно':'Разберём этот шаг'}</h3><p>{q.explanation}</p><p className="book-reference">В книге: глава {c.number}, с. {q.page} — «{q.section}».<br/><small>В предоставленном PDF это страница {q.page+book.pdfOffset}.</small></p><div className="book-feedback-actions">{!correct&&<button onClick={()=>{setSubmitted(false);setAnswer(null);}}>Попробовать снова</button>}{index<c.questions.length-1&&<button onClick={()=>next(index+1)}>Следующий вопрос →</button>}</div></div>}{passed&&<p className="book-passed" role="status">✓ Все вопросы главы пройдены. {progress[`${c.id}:read`]?'Глава завершена.':'Отметка о чтении сохраняется отдельно.'}</p>}</section><BookWalkthrough chapter={c}/></div><footer className="stage-next"><Link href="/app/book">К оглавлению</Link>{c.number<16&&<Link href={`/app/book/C${String(c.number+1).padStart(2,'0')}`}>Следующая глава →</Link>}</footer></main>;
}
function BookWalkthrough({chapter}:{chapter:Chapter}){
 const [step,setStep]=useState(0),[playing,setPlaying]=useState(false);
 useEffect(()=>{if(!playing)return;const timer=setTimeout(()=>{if(step>=chapter.steps.length-1)setPlaying(false);else setStep(step+1);},1800);return()=>clearTimeout(timer);},[playing,step,chapter]);
 return <aside className="book-walkthrough"><p className="eyebrow">РАЗБОР ПО ШАГАМ</p><h2>Как это устроено</h2><p className="walkthrough-caption">Учебная схема к главе. Переключайте шаги, чтобы проследить ход рассуждения.</p><div className="walkthrough-timeline">{chapter.steps.map((s,i)=><button key={s.title} className={i===step?'active':i<step?'visited':''} aria-current={i===step?'step':undefined} onClick={()=>{setStep(i);setPlaying(false);}}><b>{i+1}</b><span>{s.title}</span></button>)}</div><div className="walkthrough-frame" key={step}><p>{chapter.steps[step].title}</p><output>{chapter.steps[step].value}</output><p>{chapter.steps[step].explanation}</p></div><div className="walkthrough-controls"><button onClick={()=>{if(step===chapter.steps.length-1)setStep(0);setPlaying(!playing);}}>{playing?'Ⅱ Пауза':'▷ Показать шаги'}</button><button disabled={step===0} onClick={()=>{setPlaying(false);setStep(step-1);}} aria-label="Предыдущий шаг">←</button><button disabled={step===chapter.steps.length-1} onClick={()=>{setPlaying(false);setStep(step+1);}} aria-label="Следующий шаг">→</button></div></aside>;
}
